export const hinduNames = [
    "Aarav", "Aanya", "Aaditya", "Aahana", "Aarohi", "Abhay", "Advika", "Aishwarya", "Aditi", "Ajay", 
    "Akash", "Amar", "Anaya", "Anika", "Anjali", "Arjun", "Arya", "Ashok", "Bhavna", "Bhargav", 
    "Chaitanya", "Chitra", "Chetan", "Daksha", "Damini", "Darsh", "Deepak", "Dev", "Devi", "Dhruv", 
    "Dia", "Divya", "Eesha", "Ekta", "Eshaan", "Falguni", "Gaurav", "Gauri", "Gayatri", "Gopal", 
    "Harsha", "Harshita", "Ishaan", "Ishika", "Ira", "Ishwar", "Jagdish", "Jai", "Jaya", "Jayesh", 
    "Jyoti", "Kabir", "Kailash", "Kalpana", "Kalyani", "Karan", "Kavya", "Keerthi", "Kiran", "Krishna", 
    "Lakshmi", "Lata", "Luv", "Madhav", "Madhuri", "Mahesh", "Malini", "Manisha", "Mira", "Mohan", 
    "Mukesh", "Naina", "Namrata", "Narendra", "Navya", "Neha", "Niharika", "Nilesh", "Niraj", "Nisha", 
    "Nitin", "Om", "Ojas", "Pallavi", "Parth", "Pooja", "Prakash", "Pranav", "Priya", "Rahul", "Raj", 
    "Rajesh", "Rakesh", "Ram", "Ravi", "Rekha", "Riddhi", "Rishi", "Ritika", "Rohit", "Ruchi", 
    "Sachin", "Sagar", "Sai", "Sakshi", "Salil", "Sandeep", "Sanjay", "Sanya", "Sarita", "Sarthak", 
    "Satish", "Seema", "Shalini", "Shankar", "Shanti", "Sharanya", "Shashank", "Shiv", "Shivani", 
    "Shreya", "Shruti", "Siddharth", "Simran", "Sneha", "Soham", "Sonali", "Srinivas", "Suhas", 
    "Suman", "Suresh", "Swati", "Tanvi", "Tara", "Tina", "Trisha", "Tulsi", "Uday", "Ujwal", "Uma", 
    "Upasana", "Vaibhav", "Vaishali", "Varun", "Vasudev", "Vedant", "Veena", "Venkatesh", "Vibha", 
    "Vidya", "Vikas", "Vikram", "Vinay", "Vineet", "Vishal", "Vishnu", "Yash", "Yogesh", "Zara", 
    "Aadi", "Aakash", "Aarushi", "Abhinav", "Abhirami", "Adarsh", "Aditya", "Advait", "Agastya", 
    "Ahana", "Aishani", "Akanksha", "Akshay", "Alok", "Amisha", "Amit", "Amrita", "Anand", "Anisha", 
    "Anita", "Ankita", "Ankur", "Anmol", "Anushka", "Aparna", "Aradhya", "Archana", "Aryan", "Ashwini", 
    "Atul", "Avinash", "Ayush", "Bhagya", "Bhagwati", "Bhakti", "Bhanu", "Bharat", "Bhawna", "Chandra", 
    "Chandrakant", "Charan", "Chirag", "Chitra", "Darshan", "Daya", "Deepali", "Devanshi", "Dhanya", 
    "Dheeraj", "Dhriti", "Diksha", "Dipti", "Disha", "Diva", "Eeshaan", "Ekansh", "Gargi", "Gaurika", 
    "Geeta", "Geetanjali", "Gitanjali", "Gopalakrishnan", "Govind", "Gunjan", "Hansa", "Harin", "Harini", 
    "Harsh", "Harshad", "Hemant", "Hina", "Isha", "Ishanvi", "Ishika", "Ishita", "Jaidev", "Jaishree", 
    "Janhavi", "Janvi", "Jaswant", "Jatin", "Jigyasa", "Juhi", "Jyotika", "Kajal", "Kalindi", "Kamal", 
    "Kamalika", "Kanha", "Kanishk", "Kanthi", "Kartik", "Kashish", "Kashyap", "Ketaki", "Keya", "Khyati", 
    "Kiranmayi", "Kranti", "Kripa", "Kriti", "Kshitij", "Kumud", "Laksh", "Lavanya", "Leela", "Lekh", 
    "Lila", "Lina", "Lipika", "Lisha", "Lokesh", "Lopa", "Madhu", "Madhukar", "Madhulika", "Madhur", 
    "Mahadev", "Mahima", "Maitreya", "Malhar", "Manan", "Manav", "Mandira", "Mangesh", "Mansi", "Mayank", 
    "Maya", "Meera", "Megha", "Mehek", "Mihika", "Milind", "Mitali", "Mohanlal", "Monika", "Mridul", 
    "Mukta", "Mukti", "Nalini", "Namita", "Namya", "Nanda", "Nandini", "Narayan", "Natasha", "Navin", 
    "Neel", "Neeraj", "Neha", "Nidhi", "Nihar", "Niharika", "Nikita", "Nilesh", "Nimisha", "Ninad", 
    "Nirav", "Nirmala", "Nirvana", "Nisha", "Nishant", "Nita", "Nivedita", "Ojasvi", "Omkara", "Padmini", 
    "Padma", "Padmavati", "Palak", "Pallav", "Pari", "Paridhi", "Paritosh", "Parul", "Pavan", "Payal", 
    "Piyush", "Prabha", "Pradeep", "Pragya", "Prajakta", "Prakash", "Pranali", "Pranay", "Prasanna", 
    "Pratik", "Preeti", "Prem", "Prerna", "Priyanka", "Punit", "Purvi", "Pushkar", "Radha", "Radhika", 
    "Rahul", "Rajani", "Rajeev", "Rakesh", "Rama", "Raman", "Ramesh", "Ramya", "Ranbir", "Ranjan", 
    "Rani", "Rashmi", "Rati", "Raveena", "Ravi", "Reema", "Rekha", "Renuka", "Reshma", "Rhea", 
    "Riddhi", "Rishi", "Ritika", "Rohini", "Roma", "Ronak", "Ruchi", "Rudra", "Saanvi", "Sabita", 
    "Sachi", "Sadhana", "Sagarika", "Sahas", "Sahitya", "Saif", "Saisha", "Sakina", "Sakshi", 
"Alice", "Bob", "Charlie", "David", "Eve","Dev","Saurabh","Sagar","Rohit","dharmik","Eva","Rajan","Aaron","Harshad",  'Time', 'Past', 'Future', 'Dev',
    "Samarth", "Sameer", "Sana", "Sandhya", "Sangeeta", "Sanjana", "Santosh", "Saral", "Saransh", 
    "Sarita", "Sarthak", "Satish", "Satya", "Savitri", "Seema", "Shaurya", "Sheetal", "Shekhar", 
    "Shikha", "Shivendra", "Shobha", "Shraddha", "Shravani", "Shree", "Shreya", "Shubham", "Shweta", 
    "Siddhi", "Simran", "Smita", "Snehal", "Sonam", "Soumya", "Sparsh", "Srishti", "Subhash", "Sudha", 
    "Suhana", "Sujata", "Suman", "Sundar", "Sunita", "Suraj", "Surbhi", "Suresh", "Swara"
]
